//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIEU
    {
        public string MACHITIEU { get; set; }
        public string TEN { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string GHICHU { get; set; }
    }
}
