//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDICHVU
    {
        public string MAPHIEUDICHVU { get; set; }
        public string MALOAIDICHVU { get; set; }
        public string MAHOADON { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual LOAIDICHVU LOAIDICHVU { get; set; }
    }
}
